## MATRIX MULTIPLICATION

In [1]:
import numpy as np

In [3]:
A = np.array([[1, -1, 0.1],
              [2,-2,0.2]])

In [9]:
AT = A.T # Transpose

In [11]:
print(AT)

[[ 1.   2. ]
 [-1.  -2. ]
 [ 0.1  0.2]]


In [15]:
W = np.array([[3,5,7,9],
              [4,6,8,0]])

In [17]:
print(W)

[[3 5 7 9]
 [4 6 8 0]]


In [19]:
Z = np.matmul(AT, W)

In [21]:
print(Z)

[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
